version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: famicul_db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=famicul_db
    ports:
      - "5432:5432"


  backend:
    build: ./backend
    container_name: famicul_backend
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/famicul_db
