"""create visits tables

Revision ID: 848be6245534
Revises: 3b8a4ab4c0c9
Create Date: 2026-03-13 14:08:30.862776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848be6245534'
down_revision: Union[str, Sequence[str], None] = '3b8a4ab4c0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('symptom', sa.String(length=255), nullable=False),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('next_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_child_id'), 'visits', ['child_id'], unique=False)
    op.create_index(op.f('ix_visits_department_id'), 'visits', ['department_id'], unique=False)
    op.create_index(op.f('ix_visits_hospital_id'), 'visits', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_is_emergency'), 'visits', ['is_emergency'], unique=False)
    op.add_column('visit_diseases', sa.Column('visit_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'visit_diseases', 'visits', ['visit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_diseases', type_='foreignkey')
    op.drop_column('visit_diseases', 'visit_id')
    op.drop_index(op.f('ix_visits_is_emergency'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_hospital_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_department_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_child_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
