"""add memo to children

Revision ID: b870b0bc694c
Revises: d386129994f2
Create Date: 2026-05-03 12:27:17.701299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b870b0bc694c'
down_revision: Union[str, Sequence[str], None] = 'd386129994f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('memo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'memo')
    # ### end Alembic commands ###
