"""add user_id to hospitals

Revision ID: d386129994f2
Revises: b8f7f929d94a
Create Date: 2026-04-06 14:53:15.083849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd386129994f2'
down_revision: Union[str, Sequence[str], None] = 'b8f7f929d94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hospitals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_column('hospitals', 'user_id')
    # ### end Alembic commands ###
